add checkupdate pipeline

diff --git a/.gitlab-ci.yml b/.gitlab-ci.yml
--- a/.gitlab-ci.yml
+++ b/.gitlab-ci.yml
@@ -3,6 +3,43 @@ variables:
   pip: pip3 --timeout 100 --retries 10
 
 
+checkupdates:
+  image: registry.gitlab.com/fdroid/ci-images-base
+  except:
+    - pipelines
+    - schedules
+    - triggers
+  before_script:
+    - apt-get update
+    - apt-get -qy dist-upgrade
+    - pushd ..
+    - rm -rf fdroidserver
+    - mkdir fdroidserver
+    - git ls-remote https://gitlab.com/fdroid/fdroidserver.git master
+    - curl --silent https://gitlab.com/fdroid/fdroidserver/-/archive/master/fdroidserver-master.tar.gz
+        | tar -xz --directory=fdroidserver --strip-components=1
+    - export PATH="$PWD/fdroidserver:$PATH"
+    - popd
+  script:
+    # if this is a merge request fork, then only check relevant apps
+    - export EXITVALUE=0
+    - function set_error() { export EXITVALUE=1; printf "\x1b[31mERROR `history|tail -2|head -1|cut -b 6-500`\x1b[0m\n"; }
+    - if [ "$CI_PROJECT_NAMESPACE" != "fdroid" ]; then
+        git fetch https://gitlab.com/fdroid/fdroiddata.git;
+        files=`git diff --name-only --diff-filter=d FETCH_HEAD...HEAD`;
+        for f in $files; do
+          appid=`echo $f | sed -n -e 's,^metadata/\([^/][^/]*\)\.yml,\1,p'`;
+          if [ -n "$appid" ]; then
+            fdroid checkupdates --auto -v $appid || set_error;
+            git --no-pager diff --color=always;
+            diff=`git --no-pager diff`;
+            [[ $diff == '' ]] || set_error;
+            git checkout .;
+          fi;
+        done;
+      fi
+    - exit $EXITVALUE
+
 lint:
   image: registry.gitlab.com/fdroid/ci-images-base
   except:
